/**
 * Education Service for HerShiksha.
 * Scholarships, courses, skill programs, certifications, and family learning.
 */

// ── Scholarships ────────────────────────────────
const SCHOLARSHIPS = [
  // National
  { id: 'sch1', name: 'Post-Matric Scholarship for SC/ST/OBC Girls', type: 'National', provider: 'Ministry of Social Justice', eligibility: 'SC/ST/OBC girls, class 11 to PhD, family income <₹2.5L/year', benefits: 'Full tuition fees + maintenance allowance + book grant', deadline: 'October 31 (annually)', howToApply: 'Apply through National Scholarship Portal (scholarships.gov.in)', portal: 'https://scholarships.gov.in', category: 'merit-cum-means' },
  { id: 'sch2', name: 'AICTE Pragati Scholarship for Girls', type: 'National', provider: 'AICTE', eligibility: 'Girl students in AICTE-approved technical institutions, family income <₹8L/year', benefits: '₹50,000/year for tuition + incidentals', deadline: 'December (annually)', howToApply: 'Apply on AICTE portal during registration window', portal: 'https://www.aicte-india.org/schemes/students-development-schemes', category: 'technical' },
  { id: 'sch3', name: 'Begum Hazrat Mahal National Scholarship', type: 'National', provider: 'Maulana Azad Education Foundation', eligibility: 'Minority girls (class 9–12), family income <₹2L/year, 50%+ marks', benefits: '₹5,000 (class 9–10) / ₹6,000 (class 11–12) per year', deadline: 'September 30', howToApply: 'Through National Scholarship Portal', portal: 'https://scholarships.gov.in', category: 'minority' },
  { id: 'sch4', name: 'CBSE Single Girl Child Scholarship', type: 'National', provider: 'CBSE', eligibility: 'Single girl child who passed CBSE class 10 with 60%+', benefits: '₹500/month for class 11–12 (2 years)', deadline: 'December', howToApply: 'Apply through CBSE official website', portal: 'https://www.cbse.gov.in', category: 'merit' },
  { id: 'sch5', name: 'Swami Vivekananda Single Girl Child Scholarship', type: 'National', provider: 'UGC', eligibility: 'Single girl child pursuing non-professional PG courses', benefits: '₹36,200/year for social sciences, ₹38,750/year for science', deadline: 'January–March', howToApply: 'Apply through UGC portal', portal: 'https://scholarships.gov.in', category: 'higher-education' },
  // International
  { id: 'sch6', name: 'Fulbright-Nehru Scholarship (USA)', type: 'International', provider: 'USIEF', eligibility: 'Indian citizens with excellent academic record, 3+ years work experience for some categories', benefits: 'Full funding: tuition, airfare, living stipend, health insurance for Master\'s/PhD in the USA', deadline: 'February–June (varies by program)', howToApply: 'Apply at usief.org.in', portal: 'https://www.usief.org.in', category: 'international' },
  { id: 'sch7', name: 'Commonwealth Scholarship (UK)', type: 'International', provider: 'Commonwealth Scholarship Commission', eligibility: 'Citizens of Commonwealth countries, for Master\'s and PhD', benefits: 'Full tuition + airfare + living allowance at UK universities', deadline: 'October–December', howToApply: 'Through nominating agency (UGC for India)', portal: 'https://cscuk.fcdo.gov.uk', category: 'international' },
  { id: 'sch8', name: 'DAAD Scholarship (Germany)', type: 'International', provider: 'DAAD', eligibility: 'Graduates with excellent academic record for Master\'s/PhD in Germany', benefits: '€861–1,200/month + tuition + travel + insurance', deadline: 'October (for next year intake)', howToApply: 'Apply at daad.de', portal: 'https://www.daad.de', category: 'international' },
];

// ── Online Courses (Trusted Platforms) ──────────
const COURSES = [
  { id: 'c1', title: 'Computer Science Fundamentals', platform: 'Khan Academy', category: 'tech', level: 'Beginner', duration: 'Self-paced', free: true, certificate: false, url: 'https://www.khanacademy.org/computing', description: 'Learn programming, algorithms, and computing concepts from scratch. Perfect for beginners and families learning together.', familyTip: '💑 Learn coding together! Set a weekly goal to complete one unit and discuss what you learned over dinner.' },
  { id: 'c2', title: 'Google IT Support Professional Certificate', platform: 'Coursera (Google)', category: 'tech', level: 'Beginner', duration: '6 months', free: false, certificate: true, url: '#', description: 'Get job-ready for IT support roles. No prior experience needed. Recognized by top employers.', familyTip: '💑 Your partner can help quiz you on networking concepts. Study together on weekends!' },
  { id: 'c3', title: 'Financial Markets', platform: 'Coursera (Yale)', category: 'finance', level: 'Beginner', duration: '33 hours', free: true, certificate: true, url: '#', description: 'Understand stocks, bonds, insurance, and banking by Nobel laureate Robert Shiller.', familyTip: '💑 Take this course together and start planning family finances and investments as a team.' },
  { id: 'c4', title: 'The Science of Well-Being', platform: 'Coursera (Yale)', category: 'wellness', level: 'All levels', duration: '19 hours', free: true, certificate: true, url: '#', description: 'Learn evidence-based strategies for happiness. Most popular course at Yale, now free online.', familyTip: '💑 Practice gratitude exercises together. Share one good thing about your day every evening.' },
  { id: 'c5', title: 'Digital Literacy', platform: 'Khan Academy', category: 'digital', level: 'Beginner', duration: 'Self-paced', free: true, certificate: false, url: 'https://www.khanacademy.org/computing/computer-science/internet-intro', description: 'Understand the internet, cybersecurity, and digital citizenship. Essential for everyone in the digital age.', familyTip: '💑 Discuss online safety as a family. Set up secure passwords together and learn about phishing.' },
  { id: 'c6', title: 'English for Career Development', platform: 'Coursera (UPenn)', category: 'language', level: 'Intermediate', duration: '5 weeks', free: true, certificate: true, url: '#', description: 'Improve English for job applications, networking, and professional communication.', familyTip: '💑 Practice interview questions together. Your partner can play the interviewer!' },
  { id: 'c7', title: 'Introduction to Data Science', platform: 'edX (IBM)', category: 'tech', level: 'Beginner', duration: '4 weeks', free: true, certificate: false, url: '#', description: 'Explore what data science is, its career impact, and tools used by professionals.', familyTip: '💑 Explore career possibilities in data science together. Discuss how these skills could change your career.' },
  { id: 'c8', title: 'Entrepreneurship Specialization', platform: 'Coursera (Wharton)', category: 'business', level: 'Intermediate', duration: '4 months', free: false, certificate: true, url: '#', description: 'From idea to launch — build a startup with Wharton\'s business expertise.', familyTip: '💑 Brainstorm business ideas together! Your partner might have insights you haven\'t considered.' },
  { id: 'c9', title: 'Graphic Design Basics', platform: 'Canva Design School', category: 'design', level: 'Beginner', duration: '10 hours', free: true, certificate: true, url: 'https://www.canva.com/designschool/', description: 'Learn design principles, color theory, and create stunning visuals using Canva.', familyTip: '💑 Design your family event invitations together. Make learning creative and fun!' },
  { id: 'c10', title: 'Mathematics (All Levels)', platform: 'Khan Academy', category: 'academics', level: 'All levels', duration: 'Self-paced', free: true, certificate: false, url: 'https://www.khanacademy.org/math', description: 'From basic arithmetic to calculus. World-class education, free for everyone.', familyTip: '💑 Help your children with math together. Parents who learn alongside kids create stronger family bonds.' },
];

// ── Skill Development Programs ──────────────────
const SKILL_PROGRAMS = [
  { id: 'sp1', title: 'PMKVY — Free Skill Training', provider: 'Ministry of Skill Development', category: 'vocational', duration: '150–300 hours', cost: 'FREE', certificate: true, description: 'Government-backed free training in 200+ job roles with placement support and ₹8,000 reward.', targetAudience: 'School dropouts, unemployed youth, career restarters' },
  { id: 'sp2', title: 'NSDC eSKill India Portal', provider: 'NSDC', category: 'digital', duration: 'Self-paced', cost: 'FREE', certificate: true, description: '400+ free courses in IT, retail, healthcare, beauty, and more. Learn at your own pace.', targetAudience: 'Anyone looking to upskill digitally' },
  { id: 'sp3', title: 'Digital Saksharta Abhiyan (DISHA)', provider: 'CSC', category: 'digital_literacy', duration: '20 hours', cost: 'FREE', certificate: true, description: 'Basic digital literacy — learn to use computers, internet, email, and government portals.', targetAudience: 'Women with no prior computer experience' },
  { id: 'sp4', title: 'Nai Roshni — Leadership Development', provider: 'Ministry of Minority Affairs', category: 'leadership', duration: '6 days', cost: 'FREE', certificate: true, description: 'Leadership and empowerment training for minority women covering rights, health, financial literacy.', targetAudience: 'Women from minority communities' },
  { id: 'sp5', title: 'Women Entrepreneurship Platform (WEP)', provider: 'NITI Aayog', category: 'entrepreneurship', duration: 'Ongoing', cost: 'FREE', certificate: false, description: 'Mentorship, funding access, incubation, and networking for women entrepreneurs.', targetAudience: 'Aspiring and existing women entrepreneurs' },
];

// ── Certifications ──────────────────────────────
const CERTIFICATIONS = [
  { id: 'cert1', name: 'Google Professional Certificates', provider: 'Google (via Coursera)', fields: ['IT Support', 'Data Analytics', 'UX Design', 'Project Management', 'Cybersecurity'], duration: '3–6 months', cost: '₹3,000–4,000/month', value: 'Recognized by 150+ top employers. No degree required.', familyTip: '💑 Celebrate each milestone together. Completing a certificate is a family achievement!' },
  { id: 'cert2', name: 'Tally Prime + GST Certification', provider: 'Tally Education', fields: ['Accounting', 'GST Filing', 'Payroll'], duration: '2–3 months', cost: '₹5,000–10,000', value: 'Most in-demand certification for accounting jobs in India.', familyTip: '💑 Your partner can help you practice entries. Managing home finances is already preparation!' },
  { id: 'cert3', name: 'AWS Cloud Practitioner', provider: 'Amazon Web Services', fields: ['Cloud Computing', 'IT Infrastructure'], duration: '1–2 months prep', cost: '$100 exam fee', value: 'Entry-level cloud certification. Opens doors to high-paying tech roles.', familyTip: '💑 Discuss cloud technology and how it powers the apps your family uses daily.' },
  { id: 'cert4', name: 'Microsoft Office Specialist (MOS)', provider: 'Microsoft', fields: ['Word', 'Excel', 'PowerPoint', 'Outlook'], duration: '1 month prep', cost: '₹5,000–8,000 per exam', value: 'Globally recognized. Essential for any office/admin role.', familyTip: '💑 Learn Excel together — it\'s useful for household budgets, planning, and even kids\' school projects!' },
  { id: 'cert5', name: 'IELTS / TOEFL', provider: 'British Council / ETS', fields: ['English Proficiency'], duration: '2–3 months prep', cost: '₹16,000–20,000', value: 'Required for studying or working abroad. Valid for 2 years.', familyTip: '💑 Practice speaking English together at home. Even 30 minutes/day makes a big difference.' },
];

// ── Family Learning Ideas ───────────────────────
const FAMILY_LEARNING = [
  { id: 'fl1', title: 'Weekly Learning Hour', icon: '📚', description: 'Set aside one hour every week where the whole family learns something new together — a language, a skill, or a topic of interest.', howTo: 'Pick a topic on Sunday, watch a Khan Academy video together, and discuss what you learned.' },
  { id: 'fl2', title: 'Budget Planning Together', icon: '💰', description: 'Use financial literacy as a shared learning activity. Track household expenses, plan savings, and set financial goals as a team.', howTo: 'Open a shared spreadsheet, list income and expenses, and set a monthly savings target together.' },
  { id: 'fl3', title: 'Study Buddy System', icon: '🤝', description: 'Partners can take turns being each other\'s study buddy — quizzing, discussing, and motivating each other through courses.', howTo: 'Pick a course both of you are interested in, set weekly milestones, and celebrate progress together.' },
  { id: 'fl4', title: 'Digital Skills Night', icon: '💻', description: 'Spend one evening a week learning a digital skill together — from setting up email to learning basic coding or video editing.', howTo: 'Start with Khan Academy\'s Digital Literacy course. Take turns being the teacher!' },
  { id: 'fl5', title: 'Career Planning Date', icon: '🗓️', description: 'Once a month, sit together and discuss career goals, learning progress, and what support is needed. Make it positive and supportive.', howTo: 'Write down 3 career goals each, share them, and identify one actionable step for the month.' },
  { id: 'fl6', title: 'Children\'s Homework Together', icon: '👨‍👩‍👧', description: 'Both parents helping with homework normalizes learning. It shows children that education is valued by the whole family.', howTo: 'Divide subjects — one parent helps with math, the other with language. Swap every month!' },
];

// ── API Functions ────────────────────────────────
const getScholarships = (type) => type ? SCHOLARSHIPS.filter((s) => s.type.toLowerCase() === type.toLowerCase()) : SCHOLARSHIPS;
const getCourses = (category) => category ? COURSES.filter((c) => c.category === category) : COURSES;
const getSkillPrograms = () => SKILL_PROGRAMS;
const getCertifications = () => CERTIFICATIONS;
const getFamilyLearning = () => FAMILY_LEARNING;

module.exports = { getScholarships, getCourses, getSkillPrograms, getCertifications, getFamilyLearning, SCHOLARSHIPS, COURSES, SKILL_PROGRAMS, CERTIFICATIONS, FAMILY_LEARNING };
