services:
  - type: web
    name: HERSHIELD
    runtime: node
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: cd ../frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRY
        value: 15m
      - key: REFRESH_TOKEN_EXPIRY
        value: 7d
      - key: OTP_EXPIRY_MINUTES
        value: "10"
